version: "3.3"


services:
  api_ticker:
    build: .
    labels:
      - traefik.http.routers.api_ticker.entrypoints=websecure
      - traefik.http.routers.api_ticker.rule=Host(`alephium.ono.re`)
      - traefik.http.routers.api_ticker.tls=true
      - traefik.http.routers.api_ticker.tls.certresolver=letsEncrypt
      - traefik.enable=true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 2000M
    networks:
      - traefik-proxy
    ports:
      - 5002:5002
    env_file:
      - '.env'
    volumes:
      - ./api/data.db:/api/data.db

networks:
   traefik-proxy:
      external: true

