version: '3'

services:
  reverse-proxy:
    image: traefik:v2.6
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme:/etc/traefik/acme
      - ./traefik.toml:/traefik.toml

networks:
   traefik-proxy:
         external: true

