[log]
  level = "INFO"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = false
  insecure = true

[providers.docker]
  exposedbydefault = false
  watch = true

[certificatesResolvers.letsEncrypt.acme]
email = "xxxxx"
storage = "/etc/traefik/acme/acme.json"

  [certificatesResolvers.letsEncrypt.acme.httpChallenge]
  entryPoint = "web"

